# -*- coding: utf-8 -*-
"""Projeto 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MdaQUX69pHu0dBtMNLsfJ2uo90eyqwZP
"""

import pandas as pd
import sqlite3
import plotly.express as px

base = pd.read_csv("credit_risk_dataset.csv", sep = ',', encoding= 'UTF-8')
conn = sqlite3.connect("credito_banco.db")
base.to_sql("tb_credito", conn, if_exists="replace", index=False)

base

base.columns.values

# Entender os motivos que levam os clientes a pedir credito.

query1 = """
SELECT
    loan_intent AS intencao_emprestimo,
    COUNT(*) AS total_solicitacoes,
    AVG(loan_amnt) AS valor_medio_emprestimo,
    AVG(loan_int_rate) AS taxa_juros_media
FROM tb_credito
GROUP BY loan_intent
ORDER BY total_solicitacoes DESC;
"""
resultado1 = pd.read_sql_query(query1, conn)
resultado1

# Validar o aumento progressivo da taxa de inadimplência por nota de risco (de A até G)

query2 = """
SELECT
    loan_grade AS risco,
    COUNT(*) AS qtd_clientes,
    SUM(loan_status) AS total_inadiplentes,
    AVG(Loan_status) * 100 AS pct_inadimplencia
FROM tb_credito
GROUP BY loan_grade
ORDER BY risco ASC;
"""

resultado2 = pd.read_sql_query(query2, conn)
resultado2

# Comparar clientes que moram de aluguel, casa propria ou financiada.

query3 = """
SELECT
    person_home_ownership AS moradia,
    COUNT(*) as qtd_clientes,
    AVG(person_income) AS renda_media,
    AVG(loan_amnt) AS valor_medio
FROM tb_credito
GROUP BY person_home_ownership
ORDER BY qtd_clientes;
"""

resultado3 = pd.read_sql_query(query3, conn)
resultado3

# Analisar as condições de crédito oferecidas para quem já teve problemas financeiros (Y = Sim | N = Não).

query4 = """
SELECT
    cb_person_default_on_file AS historico_sujo,
    COUNT(*) as qtd_clientes,
    AVG(loan_int_rate) AS media_juros,
    AVG(loan_amnt) AS media_valor
FROM tb_credito
GROUP BY cb_person_default_on_file;
"""

resultado4 = pd.read_sql_query(query4, conn)
resultado4

# Identificar se os clientes inadimplentes (1 = Inadimplente | 0 = Em dia) comprometem uma fatia maior da renda.

query5 = """
SELECT
    loan_status AS inadimplente,
    COUNT(*) AS qtd_clientes,
    AVG(loan_percent_income) * 100 AS comprometimento_renda_medio
FROM tb_credito
GROUP BY loan_status;
"""

resultado5 = pd.read_sql_query(query5, conn)
resultado5

# Avaliar se clientes com mais anos de historico no mercado bancario são mais confiaveis.

query6 = """
SELECT
    cb_person_cred_hist_length AS anos_historico,
    COUNT(*) AS total_clientes,
    SUM(loan_status) AS total_inadimplentes,
    AVG(loan_status) * 100 AS pct_inadimplencia
FROM tb_credito
GROUP BY cb_person_cred_hist_length
HAVING total_clientes > 100
ORDER BY anos_historico ASC;
"""
resultado6 = pd.read_sql_query(query6, conn)
resultado6

print("Valores nulos atuais: ")
print(base.isnull().sum())

base['person_age'].value_counts()

base['person_income'].value_counts()

base['person_home_ownership'].value_counts()

base['person_emp_length'].value_counts()

base['loan_intent'].value_counts()

base['loan_grade'].value_counts()

base['loan_amnt'].value_counts()

base['loan_int_rate'].value_counts()

base['loan_status'].value_counts()

base['loan_percent_income'].value_counts()

base['cb_person_default_on_file'].value_counts()

base['cb_person_cred_hist_length'].value_counts()

# Troca os valores nulos pela media das suas respectivas colunas
base['person_emp_length'] = base['person_emp_length'].fillna(base['person_emp_length'].median())
base['loan_int_rate'] = base['loan_int_rate'].fillna(base['loan_int_rate'].median())

# Remove as linhas que tenham erros de digitacao
base = base[base['person_age'] < 100]
base = base[base['person_emp_length'] < base['person_age']]

print("Filtro aplicado, registros mantidos:", len(base))

# Grafico1: Taxa de Inadimplencia por Grau de Risco
fig1 = px.histogram(
    base,
    x='loan_grade',
    y='loan_status',
    histfunc='avg',
    color='loan_grade',
    labels={
        'loan_grade' : 'Grau de Risco',
        'loan_status':' Inadimplencia Media',
    },
    title='Taxa de Inadimplencia Media por Grau de Risco',
)
fig1.update_layout(template= 'plotly_white')
fig1.show()

# Grafico 2: Distribuicao dos Valores de Emprestimo
fig2 = px.histogram(
    base,
    x='loan_amnt',
    nbins=30,
    labels={'loan_amnt':'Valor do Emprestimo'},
    title='Distribuicao dos Valores de Emprestimo',
    color_discrete_sequence=['#a463fa'],
)
fig2.update_layout(template='plotly_white')
fig2.show()

# Grafico 3: Renda vs Valor do Emprestimo
fig3 = px.scatter(
    base[base['person_income']<= 300000],
    x='person_income',
    y='loan_amnt',
    color='loan_status',
    opacity=0.5,
    labels={
        'person_income':'Renda Atual',
        'loan_amnt':'Valor Solicitado',
        'loan_status': 'Status (0 = Em dia | 1 = Inadimplente)',
    },
    title='Renda vs Valor do Emprestimo',
)
fig3.update_layout(template='plotly_white')
fig3.show()

# Grafico 4: Taxa de Juros por Historico de Inadimplencia
fig4 = px.box(
    base,
    x='cb_person_default_on_file',
    y='loan_int_rate',
    color='cb_person_default_on_file',
    labels={
        'cb_person_default_on_file' : 'Historico Previo (N = nao, Y = sim)',
        'loan_int_rate': 'Taxa de Juros',
    },
    title= 'Taxa de Juros por Historico de Inadimplencia',
)
fig4.update_layout(template='plotly_white')
fig4.show()

base.to_csv('new_credit_risk.csv',index = False)
print("Arquivo gerado com sucesso")